"use client";

import { Bell, Database, ListChecks, Save, Shield, UserRound, Users, Workflow } from "lucide-react";
import { toast } from "sonner";
import { AnimatedPage } from "@/components/motion/animated-page";
import { PageHeader } from "@/components/page-header";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Checkbox } from "@/components/ui/checkbox";

export default function SettingsPage() {
  const save = (area: string) => toast.success(`${area} settings saved`);
  return (
    <AnimatedPage>
      <PageHeader title="System settings" description="Configure catalogs, follow-up rules, targets, integrations, and access policies." />
      <Tabs defaultValue="general">
        <TabsList className="flex-wrap"><TabsTrigger value="general"><Workflow /> General</TabsTrigger><TabsTrigger value="profile"><UserRound /> Profile</TabsTrigger><TabsTrigger value="assignments"><Users /> Assignments</TabsTrigger><TabsTrigger value="catalog"><ListChecks /> Catalogs</TabsTrigger><TabsTrigger value="notifications"><Bell /> Notifications</TabsTrigger><TabsTrigger value="integration"><Database /> Integrations</TabsTrigger><TabsTrigger value="security"><Shield /> Security</TabsTrigger></TabsList>
        <TabsContent value="general" className="mt-4"><Card className="bg-card/90"><CardHeader><CardTitle>Business rules</CardTitle><CardDescription>Core follow-up and reporting configuration</CardDescription></CardHeader><CardContent className="max-w-2xl space-y-5"><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label>Business timezone</Label><Input defaultValue="Asia/Karachi" /></div><div className="space-y-2"><Label>Week starts on</Label><Input defaultValue="Monday" /></div></div><label className="flex items-center gap-3 rounded-xl border p-4 text-sm"><Checkbox defaultChecked /><span><b className="block">Require reach-back date</b><span className="text-xs text-muted-foreground">Block every active lead save without a callback date.</span></span></label><label className="flex items-center gap-3 rounded-xl border p-4 text-sm"><Checkbox defaultChecked /><span><b className="block">Require follow-up comment</b><span className="text-xs text-muted-foreground">A comment and next date or terminal status clears a task.</span></span></label><Button onClick={() => save("General")}><Save /> Save changes</Button></CardContent></Card></TabsContent>
        <TabsContent value="profile" className="mt-4"><Card className="bg-card/90"><CardHeader><CardTitle>Profile and password</CardTitle><CardDescription>Update your workspace identity and login password.</CardDescription></CardHeader><CardContent className="max-w-2xl space-y-4"><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label>Name</Label><Input defaultValue="Asad" /></div><div className="space-y-2"><Label>Email</Label><Input type="email" defaultValue="asad@thefinedudes.com" /></div><div className="space-y-2"><Label>New password</Label><Input type="password" placeholder="Leave blank to keep current" /></div><div className="space-y-2"><Label>Confirm password</Label><Input type="password" /></div></div><Button onClick={() => save("Profile")}><Save /> Save profile</Button></CardContent></Card></TabsContent>
        <TabsContent value="assignments" className="mt-4"><Card className="bg-card/90"><CardHeader><CardTitle>Lead reassignment</CardTitle><CardDescription>Move active ownership while preserving the original owner history.</CardDescription></CardHeader><CardContent className="max-w-2xl space-y-4"><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label>Current agent</Label><select className="h-9 w-full rounded-lg border bg-background px-3 text-sm"><option>Uzma Khan · 116 leads</option><option>Haroon Ali · 92 leads</option></select></div><div className="space-y-2"><Label>New agent</Label><select className="h-9 w-full rounded-lg border bg-background px-3 text-sm"><option>Rohan Malik</option><option>Haroon Ali</option></select></div></div><Button onClick={() => toast.success("Selected leads reassigned")}>Reassign selected leads</Button></CardContent></Card></TabsContent>
        <TabsContent value="catalog" className="mt-4"><Card className="bg-card/90"><CardHeader><CardTitle>Admin-editable catalogs</CardTitle><CardDescription>Services and lead sources can change without code updates.</CardDescription></CardHeader><CardContent className="space-y-3">{["Website", "Google Business Profile", "SEO", "Community Management", "Ads Management", "AI Content Creation"].map((service) => <div key={service} className="flex items-center justify-between rounded-xl border p-3"><span className="text-sm font-medium">{service}</span><Button variant="ghost" size="sm" onClick={() => toast.info(`${service} editor opened`)}>Edit</Button></div>)}<Button variant="outline" onClick={() => toast.success("New catalog service added")}>+ Add service</Button></CardContent></Card></TabsContent>
        <TabsContent value="notifications" className="mt-4"><Card className="bg-card/90"><CardHeader><CardTitle>Reminder delivery</CardTitle><CardDescription>In-app is enabled for v1. External channels remain optional.</CardDescription></CardHeader><CardContent className="space-y-3"><label className="flex items-center gap-3 rounded-xl border p-4 text-sm"><Checkbox defaultChecked /> In-app due and overdue summary</label><label className="flex items-center gap-3 rounded-xl border p-4 text-sm"><Checkbox /> Email daily summary</label><label className="flex items-center gap-3 rounded-xl border p-4 text-sm"><Checkbox /> WhatsApp daily summary</label><Button onClick={() => save("Notification")}><Save /> Save reminders</Button></CardContent></Card></TabsContent>
        <TabsContent value="integration" className="mt-4"><Card className="bg-card/90"><CardHeader><CardTitle>MongoDB and CST integration</CardTitle><CardDescription>Environment-backed connections; secrets are never stored in the browser.</CardDescription></CardHeader><CardContent className="max-w-2xl space-y-4"><div className="space-y-2"><Label>MongoDB database</Label><Input value="Configured from MONGODB_URI" readOnly /></div><div className="space-y-2"><Label>CST handoff endpoint</Label><Input defaultValue="http://localhost:5000/api/integrations/sales/handoffs" /></div><Button onClick={() => save("Integration")}><Save /> Save integration</Button></CardContent></Card></TabsContent>
        <TabsContent value="security" className="mt-4"><Card className="bg-card/90"><CardHeader><CardTitle>Access and retention</CardTitle><CardDescription>Role inheritance, session, and audit policy.</CardDescription></CardHeader><CardContent className="space-y-3"><label className="flex items-center gap-3 rounded-xl border p-4 text-sm"><Checkbox defaultChecked /> Preserve user records after deactivation</label><label className="flex items-center gap-3 rounded-xl border p-4 text-sm"><Checkbox defaultChecked /> Append-only audit events</label><label className="flex items-center gap-3 rounded-xl border p-4 text-sm"><Checkbox /> Managers can view team audit history</label><Button onClick={() => save("Security")}><Save /> Save security</Button></CardContent></Card></TabsContent>
      </Tabs>
    </AnimatedPage>
  );
}
