import { CalendarDays, Download, Timer, TrendingUp } from "lucide-react";
import { AnimatedPage } from "@/components/motion/animated-page";
import { PageHeader } from "@/components/page-header";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Progress } from "@/components/ui/progress";
import Link from "next/link";

export const metadata = { title: "Reports" };

export default function ReportsPage() {
  return <AnimatedPage><PageHeader title="Sales reports" description="Every metric follows its approved event-date column." /><Card className="bg-card/90"><CardContent className="flex flex-col gap-3 p-4 sm:flex-row sm:items-end"><label className="space-y-2 text-sm"><span className="text-xs text-muted-foreground">From</span><Input type="date" defaultValue="2026-06-01" /></label><label className="space-y-2 text-sm"><span className="text-xs text-muted-foreground">To</span><Input type="date" defaultValue="2026-06-20" /></label><Button nativeButton={false} render={<Link href="/reports" />}><CalendarDays /> Apply range</Button><Button nativeButton={false} render={<Link href="/api/dashboard/export" />} variant="outline" className="sm:ml-auto"><Download /> Export CSV</Button></CardContent></Card><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Approval rate", "73.8%", 74], ["Close rate", "31.8%", 32], ["Connect rate", "34.5%", 35], ["Revenue", "$84,320", 70]].map(([label, value, percent]) => <Card key={label as string} className="bg-card/90"><CardContent className="p-5"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p><Progress value={Number(percent)} className="mt-4 h-1.5" /></CardContent></Card>)}</div><div className="grid gap-4 lg:grid-cols-2"><Card className="bg-card/90"><CardHeader><CardTitle className="flex items-center gap-2"><Timer className="size-4 text-primary" /> Pipeline cycle tracker</CardTitle><CardDescription>Average elapsed days between canonical stage dates.</CardDescription></CardHeader><CardContent className="space-y-4">{[["Submission → Approval", "2.8 days"], ["Approval → Closed-Won", "5.4 days"], ["Closed-Won → Payment", "3.2 days"], ["Submission → Payment", "11.4 days"]].map(([label, value]) => <div key={label} className="flex justify-between rounded-xl border p-4 text-sm"><span>{label}</span><strong>{value}</strong></div>)}</CardContent></Card><Card className="bg-card/90"><CardHeader><CardTitle className="flex items-center gap-2"><TrendingUp className="size-4 text-primary" /> Source conversion</CardTitle><CardDescription>Qualified pipeline performance by lead source.</CardDescription></CardHeader><CardContent className="space-y-4">{[["Cold Calling", 42], ["Meta / Facebook Ads", 64], ["Referral", 78], ["Google / SEO", 56]].map(([label, value]) => <div key={label as string}><div className="mb-2 flex justify-between text-sm"><span>{label}</span><span>{value}%</span></div><Progress value={Number(value)} /></div>)}</CardContent></Card></div></AnimatedPage>;
}
